export const campaignSchema = {
  definitions: {},
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'http://example.com/root.json',
  type: 'object',
  title: 'The Root Schema',
  required: [
    'oid',
    'eventOid',
    'promoterOid',
    'type',
    'endDate',
    'startDate',
    'notifyDate',
    'name',
    'urlSlug',
    'presentation',
    'settings',
    'registrations',
    'rewards',
    'socialActions',
    'resourceOids',
    'subscriptionLevel',
  ],
  properties: {
    oid: {
      $id: '#/properties/oid',
      type: 'integer',
      title: 'The Oid Schema',
      default: 0,
      examples: [1308],
    },
    eventOid: {
      $id: '#/properties/eventOid',
      type: 'integer',
      title: 'The Eventoid Schema',
      default: 0,
      examples: [64],
    },
    promoterOid: {
      $id: '#/properties/promoterOid',
      type: 'integer',
      title: 'The Promoteroid Schema',
      default: 0,
      examples: [21],
    },
    type: {
      $id: '#/properties/type',
      type: 'string',
      title: 'The Type Schema',
      default: '',
      examples: ['presale'],
      pattern: '^(.*)$',
    },
    endDate: {
      $id: '#/properties/endDate',
      type: 'string',
      title: 'The Enddate Schema',
      default: '',
      examples: ['2018-09-08T02:30:00.000Z'],
      pattern: '^(.*)$',
    },
    startDate: {
      $id: '#/properties/startDate',
      type: 'string',
      title: 'The Startdate Schema',
      default: '',
      examples: ['2018-08-01T02:00:00.000Z'],
      pattern: '^(.*)$',
    },
    notifyDate: {
      $id: '#/properties/notifyDate',
      type: 'string',
      title: 'The Notifydate Schema',
      default: '',
      examples: ['2018-08-02T02:00:00.000Z'],
      pattern: '^(.*)$',
    },
    name: {
      $id: '#/properties/name',
      type: 'string',
      title: 'The Name Schema',
      default: '',
      examples: ["Kevo's great campaign"],
      pattern: '^(.*)$',
    },
    urlSlug: {
      $id: '#/properties/urlSlug',
      type: 'string',
      title: 'The Urlslug Schema',
      default: '',
      examples: ['kevos-great-campaign'],
      pattern: '^(.*)$',
    },
    presentation: {
      $id: '#/properties/presentation',
      type: 'object',
      title: 'The Presentation Schema',
      required: [
        'flow',
        'color',
        'timeZone',
        'metaTitle',
        'description',
        'metaDescription',
      ],
      properties: {
        flow: {
          $id: '#/properties/presentation/properties/flow',
          type: 'array',
          title: 'The Flow Schema',
          items: {
            $id: '#/properties/presentation/properties/flow/items',
            type: 'string',
            title: 'The Items Schema',
            default: '',
            examples: ['register', 'unlock', 'share', 'invite', 'follow'],
            pattern: '^(.*)$',
          },
        },
        color: {
          $id: '#/properties/presentation/properties/color',
          type: 'string',
          title: 'The Color Schema',
          default: '',
          examples: ['#7344c0'],
          pattern: '^(.*)$',
        },
        timeZone: {
          $id: '#/properties/presentation/properties/timeZone',
          type: 'string',
          title: 'The Timezone Schema',
          default: '',
          examples: ['Australia/Sydney'],
          pattern: '^(.*)$',
        },
        metaTitle: {
          $id: '#/properties/presentation/properties/metaTitle',
          type: 'string',
          title: 'The Metatitle Schema',
          default: '',
          examples: ['RÜFÜS 2018: Register for Presale Access'],
          pattern: '^(.*)$',
        },
        description: {
          $id: '#/properties/presentation/properties/description',
          type: 'string',
          title: 'The Description Schema',
          default: '',
          examples: ['fwefewfe'],
          pattern: '^(.*)$',
        },
        metaDescription: {
          $id: '#/properties/presentation/properties/metaDescription',
          type: 'string',
          title: 'The Metadescription Schema',
          default: '',
          examples: ['Share desc'],
          pattern: '^(.*)$',
        },
      },
    },
    settings: {
      $id: '#/properties/settings',
      type: 'object',
      title: 'The Settings Schema',
      required: ['customCta', 'disablePointsSystem', 'disableEmailNotifications'],
      properties: {
        customCta: {
          $id: '#/properties/settings/properties/customCta',
          type: 'string',
          title: 'The Customcta Schema',
          default: '',
          examples: ['Register for Presale Access'],
          pattern: '^(.*)$',
        },
        disablePointsSystem: {
          $id: '#/properties/settings/properties/disablePointsSystem',
          type: 'boolean',
          title: 'The Disablepointssystem Schema',
          default: false,
          examples: [true],
        },
        disableEmailNotifications: {
          $id: '#/properties/settings/properties/disableEmailNotifications',
          type: 'boolean',
          title: 'The Disableemailnotifications Schema',
          default: false,
          examples: [true],
        },
      },
    },
    registrations: {
      $id: '#/properties/registrations',
      type: 'object',
      title: 'The Registrations Schema',
      required: ['fields', 'providers'],
      properties: {
        fields: {
          $id: '#/properties/registrations/properties/fields',
          type: 'object',
          title: 'The Fields Schema',
          required: ['emailAddress', 'firstName', 'lastName', 'mobileNumber', 'DOB', 'city'],
          properties: {
            emailAddress: {
              $id: '#/properties/registrations/properties/fields/properties/emailAddress',
              type: 'boolean',
              title: 'The Emailaddress Schema',
              default: false,
              examples: [true],
            },
            firstName: {
              $id: '#/properties/registrations/properties/fields/properties/firstName',
              type: 'boolean',
              title: 'The Firstname Schema',
              default: false,
              examples: [true],
            },
            lastName: {
              $id: '#/properties/registrations/properties/fields/properties/lastName',
              type: 'boolean',
              title: 'The Lastname Schema',
              default: false,
              examples: [true],
            },
            mobileNumber: {
              $id: '#/properties/registrations/properties/fields/properties/mobileNumber',
              type: 'boolean',
              title: 'The Mobilenumber Schema',
              default: false,
              examples: [true],
            },
            DOB: {
              $id: '#/properties/registrations/properties/fields/properties/DOB',
              type: 'boolean',
              title: 'The Dob Schema',
              default: false,
              examples: [false],
            },
            city: {
              $id: '#/properties/registrations/properties/fields/properties/city',
              type: 'boolean',
              title: 'The City Schema',
              default: false,
              examples: [false],
            },
          },
        },
        providers: {
          $id: '#/properties/registrations/properties/providers',
          type: 'object',
          title: 'The Providers Schema',
          required: ['facebook', 'spotify', 'messenger'],
          properties: {
            facebook: {
              $id: '#/properties/registrations/properties/providers/properties/facebook',
              type: 'boolean',
              title: 'The Facebook Schema',
              default: false,
              examples: [true],
            },
            spotify: {
              $id: '#/properties/registrations/properties/providers/properties/spotify',
              type: 'boolean',
              title: 'The Spotify Schema',
              default: false,
              examples: [false],
            },
            messenger: {
              $id: '#/properties/registrations/properties/providers/properties/messenger',
              type: 'boolean',
              title: 'The Messenger Schema',
              default: false,
              examples: [false],
            },
          },
        },
      },
    },
    rewards: {
      $id: '#/properties/rewards',
      type: 'object',
      title: 'The Rewards Schema',
      required: ['tiers', 'headline', 'description'],
      properties: {
        tiers: {
          $id: '#/properties/rewards/properties/tiers',
          type: 'array',
          title: 'The Tiers Schema',
          items: {
            $id: '#/properties/rewards/properties/tiers/items',
            type: 'array',
            title: 'The Items Schema',
            items: {
              $id: '#/properties/rewards/properties/tiers/items/items',
              type: 'object',
              title: 'The Items Schema',
              required: ['name', 'type', 'details'],
              properties: {
                name: {
                  $id: '#/properties/rewards/properties/tiers/items/items/properties/name',
                  type: 'string',
                  title: 'The Name Schema',
                  default: '',
                  examples: ['Prize'],
                  pattern: '^(.*)$',
                },
                type: {
                  $id: '#/properties/rewards/properties/tiers/items/items/properties/type',
                  type: 'string',
                  title: 'The Type Schema',
                  default: '',
                  examples: ['prize'],
                  pattern: '^(.*)$',
                },
                details: {
                  $id: '#/properties/rewards/properties/tiers/items/items/properties/details',
                  type: 'object',
                  title: 'The Details Schema',
                  required: ['name', 'value', 'description', 'resourceOid'],
                  properties: {
                    name: {
                      $id:
                        '#/properties/rewards/properties/tiers/items/items/properties/details/properties/name',
                      type: 'string',
                      title: 'The Name Schema',
                      default: '',
                      examples: ['Prize 1'],
                      pattern: '^(.*)$',
                    },
                    value: {
                      $id:
                        '#/properties/rewards/properties/tiers/items/items/properties/details/properties/value',
                      type: 'string',
                      title: 'The Value Schema',
                      default: '',
                      examples: [''],
                      pattern: '^(.*)$',
                    },
                    description: {
                      $id:
                        '#/properties/rewards/properties/tiers/items/items/properties/details/properties/description',
                      type: 'string',
                      title: 'The Description Schema',
                      default: '',
                      examples: ['fweewf'],
                      pattern: '^(.*)$',
                    },
                    resourceOid: {
                      $id:
                        '#/properties/rewards/properties/tiers/items/items/properties/details/properties/resourceOid',
                      type: 'integer',
                      title: 'The Resourceoid Schema',
                      default: 0,
                      examples: [0],
                    },
                  },
                },
              },
            },
          },
        },
        headline: {
          $id: '#/properties/rewards/properties/headline',
          type: 'string',
          title: 'The Headline Schema',
          default: '',
          examples: ['dsffsda'],
          pattern: '^(.*)$',
        },
        description: {
          $id: '#/properties/rewards/properties/description',
          type: 'string',
          title: 'The Description Schema',
          default: '',
          examples: ['sfaddsf'],
          pattern: '^(.*)$',
        },
      },
    },
    socialActions: {
      $id: '#/properties/socialActions',
      type: 'object',
      title: 'The Socialactions Schema',
      required: ['socialAccounts', 'shares', 'connects', 'invites'],
      properties: {
        socialAccounts: {
          $id: '#/properties/socialActions/properties/socialAccounts',
          type: 'array',
          title: 'The Socialaccounts Schema',
          items: {
            $id: '#/properties/socialActions/properties/socialAccounts/items',
            type: 'object',
            title: 'The Items Schema',
            required: [
              'save',
              'twitter',
              'youtube',
              'facebook',
              'instagram',
              'facebookEvent',
              'name',
            ],
            properties: {
              save: {
                $id: '#/properties/socialActions/properties/socialAccounts/items/properties/save',
                type: 'boolean',
                title: 'The Save Schema',
                default: false,
                examples: [false],
              },
              twitter: {
                $id:
                  '#/properties/socialActions/properties/socialAccounts/items/properties/twitter',
                type: 'string',
                title: 'The Twitter Schema',
                default: '',
                examples: ['Twittersa'],
                pattern: '^(.*)$',
              },
              youtube: {
                $id:
                  '#/properties/socialActions/properties/socialAccounts/items/properties/youtube',
                type: 'string',
                title: 'The YouTube Schema',
                default: '',
                examples: ['https://www.youtube.com/watch?v=kwk0m_mclC8'],
                pattern: '^(.*)$',
              },
              facebook: {
                $id:
                  '#/properties/socialActions/properties/socialAccounts/items/properties/facebook',
                type: 'string',
                title: 'The Facebook Schema',
                default: '',
                examples: ['https://www.facebook.com/kevinyipeio'],
                pattern: '^(.*)$',
              },
              instagram: {
                $id:
                  '#/properties/socialActions/properties/socialAccounts/items/properties/instagram',
                type: 'string',
                title: 'The Instagram Schema',
                default: '',
                examples: ['sdfaffdsfsdafs'],
                pattern: '^(.*)$',
              },
              facebookEvent: {
                $id:
                  '#/properties/socialActions/properties/socialAccounts/items/properties/facebookEvent',
                type: 'string',
                title: 'The Facebookevent Schema',
                default: '',
                examples: ['https://www.facebook.com/'],
                pattern: '^(.*)$',
              },
              name: {
                $id: '#/properties/socialActions/properties/socialAccounts/items/properties/name',
                type: 'string',
                title: 'The Name Schema',
                default: '',
                examples: ['Account #1'],
                pattern: '^(.*)$',
              },
            },
          },
        },
        shares: {
          $id: '#/properties/socialActions/properties/shares',
          type: 'object',
          title: 'The Shares Schema',
          required: ['facebook', 'twitter', 'linkedin'],
          properties: {
            facebook: {
              $id: '#/properties/socialActions/properties/shares/properties/facebook',
              type: 'boolean',
              title: 'The Facebook Schema',
              default: false,
              examples: [true],
            },
            twitter: {
              $id: '#/properties/socialActions/properties/shares/properties/twitter',
              type: 'boolean',
              title: 'The Twitter Schema',
              default: false,
              examples: [true],
            },
            linkedin: {
              $id: '#/properties/socialActions/properties/shares/properties/linkedin',
              type: 'boolean',
              title: 'The Linkedin Schema',
              default: false,
              examples: [false],
            },
          },
        },
        connects: {
          $id: '#/properties/socialActions/properties/connects',
          type: 'object',
          title: 'The Connects Schema',
          required: ['facebook', 'twitter', 'instagram', 'spotify'],
          properties: {
            facebook: {
              $id: '#/properties/socialActions/properties/connects/properties/facebook',
              type: 'boolean',
              title: 'The Facebook Schema',
              default: false,
              examples: [true],
            },
            twitter: {
              $id: '#/properties/socialActions/properties/connects/properties/twitter',
              type: 'boolean',
              title: 'The Twitter Schema',
              default: false,
              examples: [true],
            },
            instagram: {
              $id: '#/properties/socialActions/properties/connects/properties/instagram',
              type: 'boolean',
              title: 'The Instagram Schema',
              default: false,
              examples: [true],
            },
            spotify: {
              $id: '#/properties/socialActions/properties/connects/properties/spotify',
              type: 'boolean',
              title: 'The Spotify Schema',
              default: false,
              examples: [true],
            },
          },
        },
        invites: {
          $id: '#/properties/socialActions/properties/invites',
          type: 'object',
          title: 'The Invites Schema',
          required: ['link', 'messenger', 'email', 'whatsapp', 'sms'],
          properties: {
            link: {
              $id: '#/properties/socialActions/properties/invites/properties/link',
              type: 'boolean',
              title: 'The Link Schema',
              default: false,
              examples: [true],
            },
            messenger: {
              $id: '#/properties/socialActions/properties/invites/properties/messenger',
              type: 'boolean',
              title: 'The Messenger Schema',
              default: false,
              examples: [true],
            },
            email: {
              $id: '#/properties/socialActions/properties/invites/properties/email',
              type: 'boolean',
              title: 'The Email Schema',
              default: false,
              examples: [true],
            },
            whatsapp: {
              $id: '#/properties/socialActions/properties/invites/properties/whatsapp',
              type: 'boolean',
              title: 'The Whatsapp Schema',
              default: false,
              examples: [true],
            },
            sms: {
              $id: '#/properties/socialActions/properties/invites/properties/sms',
              type: 'boolean',
              title: 'The Sms Schema',
              default: false,
              examples: [true],
            },
          },
        },
      },
    },
    resourceOids: {
      $id: '#/properties/resourceOids',
      type: 'array',
      title: 'The Resourceoids Schema',
      items: {
        $id: '#/properties/resourceOids/items',
        type: 'integer',
        title: 'The Items Schema',
        default: 0,
        examples: [2640, 2653],
      },
    },
  },
};
